# Generated by Django 5.0.3 on 2024-11-28 18:00

import django.core.files.storage
import django.db.models.deletion
import v1.utils.filesave
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='CATEGORIES_ID')),
                ('categories_name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-categories_id'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orders_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ORDERS_ID')),
                ('customer_name', models.CharField(max_length=250)),
                ('customer_email', models.CharField(max_length=250)),
                ('total_item', models.IntegerField(db_default=0)),
                ('total_price', models.FloatField(db_default=0.0)),
                ('orders_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-orders_id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('products_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PRODUCTS_ID')),
                ('products_name', models.CharField(max_length=250)),
                ('products_price', models.FloatField(db_default=0.0)),
                ('products_stock', models.IntegerField(db_default=0)),
                ('products_desc', models.TextField(blank=True, null=True)),
                ('products_image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=v1.utils.filesave.filesave)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='v1.categories')),
            ],
            options={
                'ordering': ['-products_id'],
            },
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('item_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ITEM_ID')),
                ('item_price', models.FloatField(db_default=0.0)),
                ('item_stock', models.IntegerField(db_default=0)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='v1.orders')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='v1.products')),
            ],
            options={
                'ordering': ['-item_id'],
            },
        ),
    ]
